### ISSUE TITLE
Implementation guide

### ISSUE THREAD

**Issue by fabianPas** [StErMi/rarity-achievements#2]
If raritymining.com would like to integrate with the achievements expansion, it would be nice to have an implementation guide for the use of achievements. Anything you could describe regarding that?

**Comment by StErMi** [comment]
yeah, that would not be a problem, if you look at the RarityBlock and the tests you can already see the current flow. I've not made a guide yet because I would like to refine the current flow

**Comment by StErMi** [comment]
@fabianPas I've updated the readme. Let me know if you have any feedback. On the weekend I'll test it out in the testnet and I'll release the contract if everything is ok!

**Comment by fabianPas** [comment]
Great description! It's perfectly easy to integrate.
